[package]
name = "glyphwave"
version = "0.9.9"
edition = "2024"
rust-version = "1.87"
description = "Terminal screensaver and music visualizer"
license = "MIT OR Apache-2.0"
repository = "https://github.com/LuigiKraken/glyphwave"
readme = "README.md"

[dependencies]
libc = "0.2.189"
realfft = "3.5.0"
signal-hook = "0.4.4"
zbus = "5.19.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
